
[package]
name = "hak"
version = "0.1.0"
authors = ["remimimimi <valent.xarin@gmail.com>"]
edition = "2018"

[dependencies]
klog = { path = "klog" }
uart = { path = "../drivers/uart/" }
tracing = { version = "0.1.26", default-features = false }

[target.riscv64gc-unknown-none-elf.dependencies]
riscv = { path = "arch/riscv" }

[workspace]
members = [
    "bootloader",
    "arch/riscv",
    "klog",
    "xtask",
]


[profile.dev]
opt-level = 0
lto = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
